### ISSUE TITLE
Failed kn quickstart kind: docker exec exit status 137

### ISSUE THREAD

**Issue by ssdowd** [knative-sandbox/kn-plugin-quickstart#163]
trying to run `kn quickstart kind` on m1 mac Big Sur (11.16.1) and result is this:

```
> kn quickstart kind                                                                                                                                                           ─╯
Running Knative Quickstart using Kind
✅ Checking dependencies...
    Kind version is: 0.11.1

☸ Creating Kind cluster...
Creating cluster "knative" ...
 ✓ Ensuring node image (kindest/node:v1.22.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged knative-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
Command Output: I1105 20:48:04.038706     257 initconfiguration.go:247] loading configuration from "/kind/kubeadm.conf"
[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.22.2
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I1105 20:48:04.125092     257 certs.go:111] creating a new certificate authority for ca
Error: creating cluster: existing cluster: new cluster: kind create: piping output: exit status 1
Usage:
  kn-quickstart kind [flags]

Flags:
  -h, --help   help for kind

creating cluster: existing cluster: new cluster: kind create: piping output: exit status 1
Error: exit status 1
```

**Comment by psschwei** [comment]
Could be a couple of things:

* We don't actually build the plugin for m1 right now (the only Mac build right now is `kn-quickstart-darwin-amd64`). That should be possible for us to add though.

* [This issue](https://github.com/kubernetes-sigs/kind/issues/2448) has a similar error message, and the problem there was with the image used for kind. If you check the kind container logs (`kind export logs --name knative`), what do they show?

**Comment by ssdowd** [comment]
I don't think it actually creates the cluster:

```
> kind export logs --name knative
ERROR: unknown cluster "knative"

> kind get clusters
No kind clusters found.
```

**Comment by DiedeClaessens** [comment]
Can we get the M1 version? Because I had the same issue described above?

**Comment by psschwei** [comment]
Working on it... hopefully available in the near future

**Comment by DiedeClaessens** [comment]
Okay, thank you! Appreciate the hard work!

**Comment by psschwei** [comment]
M1 Plugin is now available: https://github.com/knative-sandbox/kn-plugin-quickstart/releases/tag/knative-v1.0.1

**Comment by DiedeClaessens** [comment]
I have run the new plugin but when I go on and create any service via `kn service create ...` it works fine. But when I go to the url I get Bat Gateway. Not sure if I did something wrong?

**Comment by psschwei** [comment]
A couple of questions to help debug:

* Are you using Kind or Minikube?
* What does `kn service describe hello` show? Also `kubectl get pods`?
* Are all the knative pods up and running? `kubectl get pods -n knative-serving`

**Comment by DiedeClaessens** [comment]
I am using Minikube.  
- `kn service describe hello`
![image](https://user-images.githubusercontent.com/87484823/143199795-2c48913b-a3d7-45d2-b006-9df4b77159b4.png)

![image](https://user-images.githubusercontent.com/87484823/143199945-69553313-d44c-4097-9afb-66b8611f1d6c.png)

![image](https://user-images.githubusercontent.com/87484823/143199969-8b11a003-8725-4fdc-8f6d-eec2c73d66f5.png)

**Comment by DiedeClaessens** [comment]
Because kind does not work, maybe you can point me to were to report this? 
![image](https://user-images.githubusercontent.com/87484823/143200400-bdb9d2de-1af8-4bd0-8b5e-2b67e23e57f2.png)

**Comment by psschwei** [comment]
The fact that `kubectl get pods` shows no resources seems like a problem. May want to watch what's happening with the pods when a service is created to see if that turns up any clues. (I'm not a Mac user, so I'm not able to replicate these issues, so sorry if this takes a while to debug)

For the kind not working problem, can you open a separate issue? Looks like we're [hard-coding the digest](https://github.com/knative-sandbox/kn-plugin-quickstart/blob/main/pkg/kind/kind.go#L29), so that's something we'll need to fix.

**Comment by DiedeClaessens** [comment]
It does not matter we have a cluster in the cloud I can develop with in the mean time. Do you need any further actions form me? I am happy to help!

**Comment by psschwei** [comment]
If you don't mind, could you retry running `kn quickstart minikube` and creating the service? When creating the service, can you also watch to see if the pod is created or has any problems?

**Comment by ssdowd** [comment]
`kn quickstart kind` is now working for me (v1.1.0 installed via homebrew).
