### ISSUE TITLE
Enable users to choose Kourier or Contour as a networking layer

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/kn-plugin-quickstart#18]
i.e. `kn quickstart kind --network kourier` to use kourier 
or
`kn quickstart kind --network contour` to use contour

[Inspiration](https://github.com/csantanapr/knative-kind/blob/master/install.sh#L13-L17)

**Comment by markusthoemmes** [comment]
Hadn't we discussed somewhere to not add to many options? I'm not too hung up on either of those, but I think it's then already starting to eat into the operator's realm.

**Comment by psschwei** [comment]
I had opened this since this functionality is in the current script, but per Carlos's [Slack comment](https://knative.slack.com/archives/C01JBD1LSF3/p1623882790012400?thread_ts=1623870999.006200) it isn't a main feature. No need to implement this.
