### ISSUE TITLE
increase minikube memory to 3GB

### ISSUE THREAD

**Issue by csantanapr** [knative-sandbox/kn-plugin-quickstart#246]
Today we [create the minikube without specifying the memory](https://github.com/knative-sandbox/kn-plugin-quickstart/blob/main/pkg/minikube/minikube.go#L176), the default is 2GB. we only specify 3 CPUs.

I was updating my [knative-minikube tutorial](https://github.com/csantanapr/knative-minikube) and I can't get the first sample app to deploy when I use 3CPUs and 2GB.

To reproduce:
Host: macOS
minikube: 1.25.2
k8s version: 1.23.4

Run
```
minikube config set cpus 3
minikube config set memory 2048
```
Run
```
minikube tunnel
```
Run
```
minikube start
```
Deploy
```
curl -sL https://raw.githubusercontent.com/csantanapr/knative-minikube/master/demo.sh | sh
```
It goes well to install knative serving and eventing, but deploying the first app fails
```
 🎉 Now have some fun with Serverless and Event Driven Apps 
🕹 Installing Knative Samples Apps... 
service.serving.knative.dev/hello created
Downloading hello App container image...
error: An error occurred while waiting for the condition to be satisfied: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeedingUnable to connect to the server: net/http: TLS handshake timeout
```

Increasing the memory to 3GB all the demos apps finished successfully

**Comment by csantanapr** [comment]
@psschwei have you hit any errors going thru all the examples in the knative.dev tutorial

**Comment by psschwei** [comment]
I haven't ... but I haven't tried running them on quickstart in a while.

(caveat, when I use minikube for knative dev, I give it 6GB RAM and 3 CPUs)

**Comment by csantanapr** [comment]
My bad I just double check, the default minikube is 6GB RAM not 2GB. 

This was also part of the question on telling folks what are the minimum requirements for `kn quickstart` I wanted to say 3CPUs and 2GB, but it looks like 2GB is too low for minikube at least when using hyperkit. 

So for the docs we can say that the minimum is 3CPUs and 3GB RAM for `kn quickstart kind` and `kn quickstart minikube`
That minikube will be created with default memory 6GB, but user can change to lower memory if they don't have that much memory on workstation by using `minikube config set memory 3048`

I wonder if we should create it with 3GB, config is not set, the same for CPU create with 3cpus if config is not set.

Closing this issue

**Comment by psschwei** [comment]
I'm good with adding a default RAM setting (and overrides to use user configs if present). Will open another issue for it.
