### ISSUE TITLE
minikube kn-quickstart get's broken when using sinkbindings

### ISSUE THREAD

**Issue by wmedvede** [knative-sandbox/kn-plugin-quickstart#331]
Hello team, the following issue was found when working with the kn-quickstart on minikube.
Any help or clue, will be very much appreciated.
Thanks in advance!

**minikube version: v1.26.1**

**kn version:  v20220823-local-6d86bf75, Build Date:   2022-08-23 20:27:36**

**kn-quickstart version:  v1.7.1, Build Date:   2022-08-30 09:23:39**

**Context:**
The installation procedures worked well, so we have minikube + knative profile + the tunnel, etc, all working well.

**Issue reproducer:**

Now I execute the following high level installation procedure.
(note: the procedure is for demo purposes, not for production)
A fully working reproducer can be found here:  (https://github.com/wmedvede/kogito-examples/tree/KOGITO-7765/serverless-workflow-examples/serverless-workflow-timeouts-showcase) however I believe this issue is independent of this particular example, and will happen in if we use other deployments with sinkbindings too)

1) I produce normal kubernetes deployment to provision a postgresql DB (all good)

2) I produce a normal kubernetes deployment to provision a service that uses the postgresql DB (all good)

	**Important! for this last deployment we have a sinkbinding defined.**

For the very first time, the procedure works well, i.e, the service defined in deployment 2) works well, etc.

3) Now I stop the minikube with: minikube stop -p knative (all good)

4) Now I start mimikube with: minikube start -p knative 

But this time, the error below is produced, it looks like something fails at the sinkbindings infrastructure initialization.
When this situation is produced, the initialization procedure looks to finalize, but really what we have is that the knative profile has started, but doesn't work well. Even more, If I stop minikube, and start it again, the profile is broken forever. And the only way to get things working again is by removing the knative profile and installing the kn-quicktart knative again.

$ minikube start  -p knative
😄  [knative] minikube v1.26.1 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node knative in cluster knative
🚜  Pulling base image ...
🔄  Restarting existing docker container for "knative" ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
🤦  Unable to restart cluster, will reset it: addons: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.24.3:$PATH" kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:

**stderr:
W0906 07:34:30.913565    5239 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
error execution phase addon/coredns: unable to create deployment: Internal error occurred: failed calling webhook "sinkbindings.webhook.sources.knative.dev": failed to call webhook: Post "https://eventing-webhook.knative-eventing.svc:443/sinkbindings?timeout=10s": dial tcp 10.97.131.18:443: connect: connection refused
To see the stack trace of this error execute with --v=5 or higher**

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "knative" cluster and "default" namespace by default

**Comment by psschwei** [comment]
Thanks for opening the issue!

It _looks_ like what's happening is that one of the knative webhook is intercepting the coreDNS deployment, but there's nothing there (as the cluster isn't up yet), so it's throwing the error you're seeing.

That said, quickstart is really meant for ephemeral use, and it's recommended to spin up a new cluster from scratch rather than stopping/starting minikube.

**Comment by wmedvede** [comment]
ok, I'll re-create the cluster in these situations.
Thanks for the pointer.

**Comment by wmedvede** [comment]
Closing since it the recommendation is to spin up a new cluster each time.
