### ISSUE TITLE
Non-interactive quickstart

### ISSUE THREAD

**Issue by corinz** [knative-sandbox/kn-plugin-quickstart#338]
Is it possible to use quickstart on an _existing_ cluster without having to use the prompt? e.g.

```
% kn quickstart kind --name local
Running Knative Quickstart using Kind
✅ Checking dependencies...
    Kind version is: 0.15.0

Knative Cluster kind-local already installed.
Delete and recreate [y/N]:
```

Ideally, we could run the entire command non-interactively like: `kn quickstart kind --name local --no-tty` or a `-y` or `-n` flag. Your thoughts?

**Comment by psschwei** [comment]
Quickstart wasn't intended to be an installer, so I don't think that's something we'd do. Instead, you might want to look into the [operator plugin](https://github.com/knative-sandbox/kn-plugin-operator) or scripting the yaml install like @csantanapr did with [KonK](https://github.com/csantanapr/knative-kind).
