### ISSUE TITLE
Release (1.8) is broken

### ISSUE THREAD

**Issue by nomagick** [knative-sandbox/kn-plugin-quickstart#354]
Somehow `ServingVersion` etc. are not set.

https://github.com/knative-sandbox/kn-plugin-quickstart/blob/a269cb4b9ac0661550b54e1315b2ae655c7dc319/pkg/install/install.go#L25-L27

Log: 
```
🍿 Installing Knative Serving v ...
```

**Comment by psschwei** [comment]
Looks like the new version got cut before serving was ready, will get a patch release out to fix it shortly

**Comment by psschwei** [comment]
Fixed in v1.8.1: https://github.com/knative-sandbox/kn-plugin-quickstart/releases/tag/knative-v1.8.1
