### ISSUE TITLE
Error -  unable to read URL "https://github.com/knative/serving/releases/download/knative-v/serving-crds.yaml", server reported 404 Not Found, status code=404

### ISSUE THREAD

**Issue by jeffreywstevens** [knative-sandbox/kn-plugin-quickstart#355]
I am just getting started. I had high hopes but there seems to be a recent release. 

I just tried to install the kn-quickstart and got this at the end.

Installing Knative Serving v ...
error: unable to read URL "https://github.com/knative/serving/releases/download/knative-v/serving-crds.yaml", server reported 404 Not Found, status code=404

Is the installation hosed or not?

**Comment by psschwei** [comment]
See #354 -- pushing a fix out now
