### ISSUE TITLE
Kind - Timeout Eventually after In-memory channel installed...

### ISSUE THREAD

**Issue by jeffreywstevens** [knative-sandbox/kn-plugin-quickstart#359]
I had high hopes to show this off tomorrow.  Any ideas?

broker-filter-hpa and broker-ingress-hpa are stuck at 70%. 

mt-broker-controller and mt-broker-ingress are 0/1 ready.

Is anywhere else (AKS, GKE, Amazon) that is easier to install?

**Comment by psschwei** [comment]
Kind or minikube? Anything in the pod events / logs?

**Comment by jeffreywstevens** [comment]
It was on KIND. Minikube throws a CPU error immediately.

Here is what appears to be a significant event:
FailedScheduling               pod/mt-broker-ingress-5c4d45dfd6-zb5ng       0/1 nodes are available: 1 Insufficient CPU.

I found the above. Seems to be the problem preventing the rest of the start up.
How do I provide more CPU to this? My underlying hardware is strong. I have an i9 8 core with 64GB RAM  How do I provide more nodes to this KIND cluster? Would that help?

**Comment by psschwei** [comment]
I think it depends on how you're running kind. For example, if you're using Docker Desktop or something like that you may need to adjust the resource limits. But beyond that, I don't know -- you may want to check with the [kind community](https://kind.sigs.k8s.io/#community) if you need more help.

**Comment by lionelvillard** [comment]
I'm running quickstart+kind+serving+eventing+kafka with no problem on a 4 years old Mac. A Paul said, try adjusting Docker Desktop limits if that's what you are using.

**Comment by jeffreywstevens** [comment]
Unfortunately, I left my MacBook a few thousand miles away. I tried adjusting the WSL 2 .wslconfig and didn't get the results I wanted. I did some other things, not methodicallly.

So I created a 3 node KIND cluster named knative first, and then did the quickstart. Success!

Thanks for your help, in helping me get to a solution.
