### ISSUE TITLE
kn-quickstart is blocked by MacOS

### ISSUE THREAD

**Issue by VladyslavKurmaz** [knative-sandbox/kn-plugin-quickstart#371]
Hi Team.
I'm trying to setup knative under MacOS  using quickstart plugin and this manual https://knative.dev/docs/getting-started/quickstart-install/#install-the-knative-quickstart-plugin

Unfortunately, when I try to run next command
> kn quickstart --help

MacOS blocks execution, please see screenshot below.

Any ideas how this issue can be fixed.
Thanks in advance.

<img width="272" alt="Screenshot 2022-12-05 at 10 05 03" src="https://user-images.githubusercontent.com/1977961/205585228-347424d2-3e12-46ce-846a-996bbb49b4cb.png">

**Comment by psschwei** [comment]
What version of the quickstart plugin are you using? And what version of MacOS?

I don't use a Mac, but based on a quick web search it looks like you may need to authorize the app in the System Preferences menu.

**Comment by lance** [comment]
Hi @VladyslavKurmaz. When I have "App store and identified developers" selected in my security settings, I am given the option to open the file or not.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/15952/205713294-9bc543db-0c5f-4521-a06a-b34b2fcf9bb3.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/15952/205713394-305fc717-8034-4741-990b-eac5728e9116.png">
Can you try this to see if it helps you out?
