### ISSUE TITLE
Add local registries to quickstart install

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/kn-plugin-quickstart#374]
As per @evankanderson 's comment on [slack](https://knative.slack.com/archives/C93E33SN8/p1673043271952749), it'd be good to add local registries to the quickstart installs:

Kind: https://kind.sigs.k8s.io/docs/user/local-registry/

Minikube: https://minikube.sigs.k8s.io/docs/handbook/registry/#enabling-insecure-registries

/good-first-issue

**Comment by ehudyonasi** [comment]
I would like to grab this issue.

**Comment by psschwei** [comment]
Awesome!
/assign @ehudyonasi
