### ISSUE TITLE
Image pull from priveate registry with self signed CA stopped working after v1.9.0 release

### ISSUE THREAD

**Issue by nomagick** [knative-sandbox/kn-plugin-quickstart#385]
After the latest v1.9.0 was released, our CI was broken.

Our CI automatically downloads latest minikube/kn/kn-quickstart and runs
- minikube config set cpus 2
- minikube config set EmbedCerts true
- kn quickstart minikube --install-serving

The installation seemed successful, but when deploying services, it gets:
 
Revision (rev) failed with message: Unable to fetch image (the image): failed to resolve image to digest: Get (the image): x509: certificate signed by unknown authority.

**Comment by psschwei** [comment]
I'm not able to reproduce using a basic hello-world app.

That said, I'd check [what's changed in v1.9](https://knative.dev/blog/releases/announcing-knative-v1-9-release/#serving) and see if anything there jumps out.
