### ISSUE TITLE
Check for cluster readiness in cluster creation step

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/kn-plugin-quickstart#75]
In the current cluster creation process, we sleep for a few seconds to ensure that the cluster has been created (for both [Kind](https://github.com/knative-sandbox/kn-plugin-quickstart/blob/main/pkg/kind/kind.go#L156) and Minikube clusters) before running any `kubectl` commands against it. 

However, this is a hacky way to create the cluster. It would be much nicer if we were able to test for cluster creation somehow rather than using sleep.

**Comment by markusthoemmes** [comment]
kind actually has a way, see https://github.com/knative-sandbox/kn-plugin-quickstart/pull/84

**Comment by psschwei** [comment]
Thanks @markusthoemmes !!
