### ISSUE TITLE
 kn quickstart version doesnt work

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/kn-plugin-quickstart#88]
## Actual Behaviour
```
 ~ % kn quickstart version

Version:
Build Date:
Git Revision:
```

## Expected Behaviour
Display the version 
Also if this is not exposed, not sure if it also impacts users from upgrading using something like homebrew 🤔 

Overall, love how simple this makes it to get a cluster so thank you for this 😄

**Comment by psschwei** [comment]
Thanks for raising this!

/assign

**Comment by psschwei** [comment]
Above PR didn't fix the issue, still investigating
