### ISSUE TITLE
Delete old knative resources when installing on an existing cluster

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/kn-plugin-quickstart#97]
If the quickstart plugin detects an existing Kind cluster, it prompt the user with the choice deleting and recreating the cluster. If the user chooses to NOT delete their existing cluster, there can be conflicts when installing Knative over top of an existing installation. 

It might be a good idea to check to see if the knative namespaces exist, and if so to re-prompt the user to either delete / recreate the cluster or abort.

**Comment by ehudyonasi** [comment]
@psschwei can you assign it to me? and can you share the details on that Slack message? My guess is to delete the crds, deployments, cm, etc?

**Comment by psschwei** [comment]
Looking back at this one, I think it might be better to abort the install if we find an existing knative namespace, rather than trying to delete the existing resources. 

The quickstart clusters are supposed to be ephemeral, so I don't think it's a good idea to start worrying about updating installs, etc. with this plugin. It'd be better if we detect an existing install to alert the user of that and re-run the "ask if you want to delete the cluster" bit.

If you're still interested in working this, you should be able to assign yourself by commenting `/assign @ehudyonasi`.
